services:
  processor:
    build:
      context: .
      dockerfile: /Shuffle.DataProcessor/Dockerfile
    ports:
      - 8080:8080
      - 8080:8081
    image: processor/latest
    networks:
      - coding-test-network 
  shuffle:
    build:
      context: .
      dockerfile: /Shuffle.Api/Dockerfile
    ports:
      - 8080:8080
      - 8080:8081
    depends_on:
      processor:
        condition: service_healthy
    image: shuffle/latest
    networks:
      - coding-test-network 

networks:
  coding-test-network:
    driver: bridge
    name: coding-test-network