services:
  processor:
    build:
      context: .
      dockerfile: /Shuffle.DataProcessor/Dockerfile
    ports:
      - 8080:8080
      - 8080:8081
    image: processor/latest
    networks:
      - coding-test-network 

networks:
  coding-test-network:
    driver: bridge
    name: coding-test-network